---
- name: Configure networking on hosts
  hosts: swarm_nodes
  tasks:
    - name: Stop systemd-resolved service and disable it
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false
      become: true

    - name: Populate /etc/resolv.conf with Cloudflare DNS
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 1.1.1.1
          nameserver 8.8.8.8
        owner: root
        group: root
        mode: '0644'
        force: yes
      become: true

- hosts: swarm_nodes
  vars:
    journald_persistent: true
    journald_max_disk_size: 6000
    journald_compression: true
  become: true
  roles:
    - linux-system-roles.journald

- import_playbook: provision_ssh.yml
- import_playbook: provision_swarm.yml
- import_playbook: provision_gluster.yml
- import_playbook: provision_keepalived.yml

