- name: Provision GlusterFS
  hosts: swarm_nodes
  tasks:
    - name: Install GlusterFS
      ansible.builtin.apt:
        name: glusterfs-server
        state: present
      become: true

    - name: Start GlusterFS
      ansible.builtin.systemd_service:
        name: glusterd
        state: started
        enabled: true
      become: true

    - name: Check if directory for gluster data exists
      ansible.builtin.stat:
        path: /data/brick1/gv0
      register: gluster_dir

    - name: Ensure directory for gluster data exists
      ansible.builtin.file:
        path: /data/brick1/gv0
        state: directory
        recurse: true
      become: true
      when: not gluster_dir.stat.exists

    - name: Probe GlusterFS peers
      command: gluster peer probe {{ item }}
      with_items: "{{ groups['swarm_nodes'] | difference([inventory_hostname]) | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
      become: true
      register: probe_result
      changed_when: "'already in peer list' not in probe_result.stdout"
      when: inventory_hostname in groups['swarm_managers'][0]

    - name: Create gluster volume
      command: |
        gluster volume create gv0 replica {{ groups['swarm_nodes'] | length }} \
          {{
            groups['swarm_nodes']
            | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
            | map('regex_replace', '(.+)', '\1:/data/brick1/gv0')
            | join(' ')
          }} \
          force
      become: true
      register: create_result
      changed_when: "'already exists' not in create_result.stderr"
      failed_when: ('already exists' not in create_result.stderr) and create_result.rc != 0
      when: inventory_hostname in groups['swarm_managers'][0]

    - name: Start gluster volume
      command: gluster volume start gv0
      become: true
      register: start_result
      changed_when: "'already started' not in start_result.stderr"
      failed_when: ('already started' not in start_result.stderr) and start_result.rc != 0
      when: inventory_hostname in groups['swarm_managers'][0]

    - name: Check if directory for gluster mount dir exists
      ansible.builtin.stat:
        path: /mnt/gluster
      register: gluster_mount_dir

    - name: Ensure directory for gluster mount dir exists
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
        owner: admin
        group: docker
        recurse: true
      become: true
      when: not gluster_mount_dir.stat.exists

    - name: Mount the gluster volume
      ansible.posix.mount:
        src: localhost:/gv0
        path: /mnt/gluster
        state: mounted
        fstype: glusterfs
        opts: defaults,_netdev,backupvolfile-server=localhost
      become: true
