---
- name: Create TVBot service
  hosts: swarm_managers[0]
  tasks:
    - name: Ensure mongo appdata directory exists
      ansible.builtin.file:
        path: /mnt/gluster/appdata/mongo_tvbot_prod
        state: directory
        owner: 1001
        group: root
        mode: '0777'
        recurse: yes
      become: true

    - set_fact:
        mongo_root_password: "{{ lookup('bitwarden.secrets.lookup', '4a0e11c6-6433-4ca2-af64-b20f0053115a') }}"

    - community.general.docker_stack:
        name: tvbot-prod
        state: present
        compose:
          - version: '3.8'
            services:
              mongodb-primary:
                image: ghcr.io/xavidop/mongodb:7.0-debian-12
                environment:
                  - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
                  - MONGODB_REPLICA_SET_MODE=primary
                  - MONGODB_ROOT_PASSWORD={{ mongo_root_password }}
                  - MONGODB_REPLICA_SET_KEY=cdlfmckwolrmjcnsolrj
                volumes:
                  - '/mnt/gluster/appdata/mongo_tvbot_prod:/bitnami/mongodb'
                deploy:
                  mode: replicated
                  replicas: 1
              mongodb-secondary:
                image: ghcr.io/xavidop/mongodb:7.0-debian-12
                depends_on:
                  - mongodb-primary
                environment:
                  - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
                  - MONGODB_REPLICA_SET_MODE=secondary
                  - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
                  - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD={{ mongo_root_password }}
                  - MONGODB_REPLICA_SET_KEY=cdlfmckwolrmjcnsolrj
                deploy:
                  mode: replicated
                  replicas: 1
              mongodb-arbiter:
                image: ghcr.io/xavidop/mongodb:7.0-debian-12
                depends_on:
                  - mongodb-primary
                environment:
                  - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
                  - MONGODB_REPLICA_SET_MODE=arbiter
                  - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
                  - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD={{ mongo_root_password }}
                  - MONGODB_REPLICA_SET_KEY=cdlfmckwolrmjcnsolrj
                deploy:
                  mode: replicated
                  replicas: 1
              tvbot:
                image: ghcr.io/cbackas/tvbot:latest
                depends_on:
                  - mongodb-primary
                  - mongodb-secondary
                  - mongodb-arbiter
                environment:
                  - REGISTER_COMMANDS=true
                  - DISCORD_CLIENT_ID={{ lookup('bitwarden.secrets.lookup', 'd6f03b5b-9f05-4e92-ab48-b2080061a5d8') }}
                  - DISCORD_TOKEN={{ lookup('bitwarden.secrets.lookup', 'e29262b8-d1d1-4b01-819a-b2080061cf32') }}
                  - DISCORD_GUILD_ID={{ lookup('bitwarden.secrets.lookup', '6fc1d0b5-3099-484e-8160-b2080061dc27') }}
                  - TVDB_API_KEY={{ lookup('bitwarden.secrets.lookup', 'cf58ab16-162f-4a49-84dc-b2080062035a') }}
                  - TVDB_USER_PIN={{ lookup('bitwarden.secrets.lookup', 'a62de286-5082-4fd7-9b5d-b20800621118') }}
                  - DATABASE_URL=mongodb://root:{{ mongo_root_password }}@mongodb-primary:27017,mongodb-secondary:27017/tvbot?authSource=admin
                  - HEALTHCHECK_URL={{ lookup('bitwarden.secrets.lookup', '0d922fba-1ae7-4583-832f-b20800623461') }}
                  - TZ=America/Chicago
                deploy:
                  mode: replicated
                  replicas: 1

