---
- name: Create Technitium DNS service
  hosts: swarm_managers[0]
  tasks:
    - name: Ensure technitium appdata directory exists
      ansible.builtin.file:
        path: /mnt/gluster/appdata/technitium/data
        state: directory
        recurse: yes

    - name: Start the technitium service
      community.general.docker_stack:
        name: dns-server
        state: present
        compose:
          - version: '3.8'
            services:
              technitium:
                image: technitium/dns-server:latest
                ports:
                  - "5380:5380/tcp" # DNS web console (HTTP)
                  - "53:53/udp" # DNS service
                  - "53:53/tcp" # DNS service
                  - "853:853/tcp" # DNS-over-TLS service
                environment:
                  - DNS_SERVER_DOMAIN=dns1.zac.arpa # the primary domain name used by this DNS Server to identify itself.
                  - DNS_SERVER_LOG_USING_LOCAL_TIME=true
                volumes:
                  - /mnt/gluster/appdata/technitium/data:/etc/dns
                sysctls:
                  - net.ipv4.ip_local_port_range=1024 65000
                deploy:
                  mode: replicated
                  replicas: 1

