---
- name: Start Technitium DNS service
  hosts: swarm_managers[0]
  tasks:
    - name: Start the technitium service
      community.general.docker_stack:
        name: dns-server
        state: present
        compose:
          - version: '3.8'
            services:
              technitium:
                image: technitium/dns-server:latest
                ports:
                  - "5380:5380/tcp" # DNS web console (HTTP)
                  - "53:53/udp" # DNS service
                  - "53:53/tcp" # DNS service
                  - "853:853/tcp" # DNS-over-TLS service
                environment:
                  - DNS_SERVER_DOMAIN=dns1.zac.arpa # the primary domain name used by this DNS Server to identify itself.
                  - DNS_SERVER_LOG_USING_LOCAL_TIME=true
                volumes:
                  - /mnt/gluster/appdata/technitium/data:/etc/dns
                sysctls:
                  - net.ipv4.ip_local_port_range=1024 65000
                deploy:
                  mode: replicated
                  replicas: 1

- name: Get TVBot Secrets
  hosts: localhost
  tasks:
    - add_host:
        name: "{{ groups['swarm_managers'][0] }}"
        discord_client_id: "{{ lookup('bitwarden.secrets.lookup', 'd6f03b5b-9f05-4e92-ab48-b2080061a5d8') }}"
        discord_token: "{{ lookup('bitwarden.secrets.lookup', 'e29262b8-d1d1-4b01-819a-b2080061cf32') }}"
        discord_guild_id: "{{ lookup('bitwarden.secrets.lookup', '6fc1d0b5-3099-484e-8160-b2080061dc27') }}"
        tvdb_api_key: "{{ lookup('bitwarden.secrets.lookup', 'cf58ab16-162f-4a49-84dc-b2080062035a') }}"
        tvdb_user_pin: "{{ lookup('bitwarden.secrets.lookup', 'a62de286-5082-4fd7-9b5d-b20800621118') }}"
        database_url: "{{ lookup('bitwarden.secrets.lookup', '4ac6ad16-2a9d-4fa7-a524-b208006221ff') }}"
        healthcheck_url: "{{ lookup('bitwarden.secrets.lookup', '0d922fba-1ae7-4583-832f-b20800623461') }}"
      changed_when: false

- name: Start TVBot service
  hosts: swarm_managers[0]
  tasks:
    - name: Start the tvbot service
      community.general.docker_stack:
        name: tvbot
        state: present
        compose:
          - version: '3.8'
            services:
              tvbot:
                image: ghcr.io/cbackas/tvbot:latest
                environment:
                  - DISCORD_CLIENT_ID={{ discord_client_id }}
                  - DISCORD_TOKEN={{ discord_token }}
                  - DISCORD_GUILD_ID={{ discord_guild_id }}
                  - TMDB_API_KEY={{ tmdb_api_key }}
                  - TVDB_API_KEY={{ tvdb_api_key }}
                  - TVDB_USER_PIN={{ tvdb_user_pin }}
                  - DATABASE_URL={{ database_url }}
                  - REGISTER_COMMANDS=true
                  - HEALTHCHECK_URL={{ healthcheck_url }}
                  - TZ=America/Chicago
                deploy:
                  mode: replicated
                  replicas: 1

