# fly.toml app configuration file generated for zacs-uptime-kuma on 2024-06-19T15:14:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zacs-uptime-kuma'
primary_region = 'den'

[build]
  image = 'louislam/uptime-kuma:1'

[[mounts]]
  source = 'kuma_data'
  destination = '/app/data'
  initial_size = '2'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 1
